---
- name: reset state of /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    state: file
  tags:
    - molecule-notest

- name: fill /etc/resolv.conf
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - molecule-notest
